# Generated by Django 5.0.6 on 2024-05-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0001_create_user_schema'),
    ]

    operations = [migrations.RunSQL(
        sql=[
            ("CREATE EXTENSION IF NOT EXISTS pgcrypto"),
            ("""CREATE TABLE IF NOT EXISTS "spaces" (
             "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
             "name" varchar NOT NULL,
             "description" text,
             "created_at" timestamp NOT NULL DEFAULT NOW()
             );""")
             ],
        reverse_sql=[
            ("DROP TABLE IF EXISTS spaces"),
            ("DROP EXTENSION IF EXISTS pgcrypto"),
            ]
            )
    ]
