# Generated by Django 5.0.6 on 2024-05-26 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_create_space_table'),
    ]

    operations = [migrations.RunSQL(
        sql=[
            ("""CREATE TABLE IF NOT EXISTS "users" (
             "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
             "username" varchar NOT NULL UNIQUE,
             "password" varchar NOT NULL,
             "role" varchar NOT NULL,
             "created_at" timestamp NOT NULL DEFAULT NOW()
             );""")
             ],
        reverse_sql=[
            ("DROP TABLE IF EXISTS TABLE users"),
            ]
            )
    ]
