# Generated by Django 5.0.6 on 2024-05-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0004_create_session_table'),
    ]

    operations = [migrations.RunSQL(
        sql=[
            ("""CREATE TABLE IF NOT EXISTS "tasks" (
             "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
             "session_id" uuid NOT NULL,
             "title" varchar NOT NULL,
             "description" text,
             "status" varchar NOT NULL,
             "created_at" timestamp NOT NULL DEFAULT NOW(),
             FOREIGN KEY ("session_id") REFERENCES "sessions" ("id")
             );"""),
             ("""CREATE INDEX idx_tasks_session_id ON "tasks" ("session_id");"""),
             ],
        reverse_sql=[
            ("""DROP INDEX IF EXISTS idx_tasks_session_id;"""),
            ("""DROP TABLE IF EXISTS "tasks";"""),
            ]
            )
    ]