# Generated by Django 5.0.6 on 2024-05-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0005_create_task_table'),
    ]

    operations = [migrations.RunSQL(
        sql=[
            ("""CREATE TABLE IF NOT EXISTS "leaderboard" (
             "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
             "session_id" uuid NOT NULL,
             "user_id" uuid NOT NULL,
             "score" int NOT NULL,
             "created_at" timestamp NOT NULL DEFAULT NOW(),
             FOREIGN KEY ("session_id") REFERENCES "sessions" ("id"),
             FOREIGN KEY ("user_id") REFERENCES "users" ("id")
             );"""),
             ("""CREATE INDEX idx_leaderboard_session_id ON "leaderboard" ("session_id");
              CREATE INDEX idx_leaderboard_user_id ON "leaderboard" ("user_id");
              """),
             ],
        reverse_sql=[
            ("""DROP INDEX IF EXISTS idx_leaderboard_session_id;
             DROP INDEX IF EXISTS idx_leaderboard_user_id;"""),
            ("""DROP TABLE IF EXISTS "leaderboard";"""),
            ]
            )
    ]
