# Generated by Django 5.0.6 on 2024-05-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0007_create_user_statistic_table'),
    ]

    operations = [migrations.RunSQL(
        sql=[
            ("""CREATE TABLE IF NOT EXISTS "space_members" (
             "space_id" uuid NOT NULL,
             "user_id" uuid NOT NULL,
             "joined_at" timestamp NOT NULL DEFAULT NOW(),
             PRIMARY KEY ("space_id", "user_id"),
             FOREIGN KEY ("space_id") REFERENCES "spaces" ("id"),
             FOREIGN KEY ("user_id") REFERENCES "users" ("id")
             );"""),
             ("""CREATE INDEX idx_space_members_user_id ON "space_members" ("user_id");
              CREATE INDEX idx_space_members_space_id ON "space_members" ("space_id");"""),
             ],
        reverse_sql=[
            ("""DROP INDEX IF EXISTS idx_space_members_user_id;
             DROP INDEX IF EXISTS idx_space_members_space_id;"""),
            ("""DROP TABLE IF EXISTS "space_members";"""),
            ]
            )
    ]
