# Generated by Django 5.0.6 on 2024-05-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0008_create_space_member_table'),
    ]

    operations = [migrations.RunSQL(
        sql=[
            ("""CREATE TABLE IF NOT EXISTS "users"."role" (
             "role_id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
             "role_name" varchar NOT NULL,
             "created_at" timestamp NOT NULL DEFAULT NOW(),
             FOREIGN KEY ("role_id") REFERENCES "users" ("role")
             );"""),
             ],
        reverse_sql=[
            ("""DROP TABLE IF EXISTS "users"."role";"""),
            ]
            )
    ]
