# Generated by Django 5.0.6 on 2024-06-03 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # operations = [
    #     migrations.RunSQL(
    #         sql='''
    #         CREATE TABLE "app_users_profile" (
    #             "id" bigint NOT NULL PRIMARY KEY,
    #             "image" varchar(100) NULL,
    #             "displayName" varchar(200) NULL,
    #             "info" text NULL,
    #             "user_id" integer NOT NULL UNIQUE REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED
    #         );
    #         ''',
    #         reverse_sql="DROP TABLE IF EXISTS app_users_profile;",
    #     ),
    # ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('displayName', models.CharField(blank=True, max_length=200, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
